// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oesouojwqetlskwtgclj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lc291b2p3cWV0bHNrd3RnY2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTQwMDksImV4cCI6MjA3MzM3MDAwOX0.BsboHez0MO-ShCK0sy5-8RioA7b1rhhkUi-xQ0RmT1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});